- models/AMICO_ACTIVEAX.m
- models/AMICO_NODDI.m
- models/AMICO_WATERFREE.m
- optimization/AMICO_Fit.m
I made this refactoring to ease the porting to dipy. There is now an outer loop that iterates over all the voxels, perform operations common to all models and then calls the specific Fit() method of the actual model
> moved loop over voxels in main Fit() function

- matlab/optimization/AMICO_Fit.m
- python/amico/core.py
I added 2 lines to fix the calibration scaling parameters.
Daisuke
> Set scaling slope to 1 and scaling intercept to 0

- matlab/other/AMICO_fsl2scheme.m
Also
- Add explanatory output
- Warn if change in b-values is large
- Write scheme file values to 6 decimal places
> ENH: Add option to force b-values to pre-defined shells

- python/amico/util.py
Added python implementation of fsl2scheme script to create scheme file from bvals/bvecs file.
> Added python implementation of fsl2scheme

- python/amico/util.py
Nice that you provide a scheme making function, I remember having to convert those with camino before.
> fixed typo

- python/amico/models.py
- python/doc/demos/ACTIVEAX_01.md
- python/doc/demos/README.md
Adapted original matlab tutorial to match AMICO's python implementation
> Tutorial for ActiveAx using python implementation

- python/amico/models.py
Fixes a bug in the previous PR.
> BF: concatenation of single b0 with dwi array

- amico/models.py
This model is intended to be used for testing, but it can be rather useful in combination to COMMIT.
> Added model considering only volume fractions

- amico/lut.py
Thank for your work, I think this is the most safe way to get the index in integer, even with different numpy versions
> bug for lut.py

- amico/models.py
This should solve #44.
Needs the isExvivo flag to be set as follows:
```
ae.model.set( dPar, dIso, IC_VFs, IC_ODs, True )
```
> BUG: should solve issue #44

- amico/scheme.py
Shell idx extracted from equal rows instead of b-value (different rows can have the same b-value)
Should solve Issue #50
> BUG: Issue #50

- README.md
- setup.py
Add **dipy** to `install_requires` list. Once spams is on pypi, it can be added as well to simplify the installation process.
> DOC: slight simplification for the installation process

- amico/core.py
- amico/preproc.py
- doc/demos/README.md
- doc/demos/preproc_debias.md
Allows to remove the rician bias from the DWI volume using a method similar to [(Kaden et al., MRM, 2016)](https://www.ncbi.nlm.nih.gov/pubmed/25974332), implemented by @ejcanalesr and @davidrs06
> Added rician debias option in preprocessing step

- amico/core.py
> Changed print command to avoid error in new version of python

- amico/lut.py
- setup.py
I created a pull request with the code from #74.
> Better python3 compatibility. 

- amico/lut.py
> Bug 74 fix

- amico/core.py
- amico/lut.py
- amico/models.py
- amico/preproc.py
- amico/scheme.py
Since the new release of dipy amico is not working properly
Will need some validation but so far seems to work.
> fix dependancy to old dipy.utils.six.moves

- CHANGELOG.md
- amico/util.py
- setup.py
PR to fix warning messages used in `util.py`, the problem was reported in #109 .
> Fix warning message in util.py

- CHANGELOG.md
- amico/__init__.py
- amico/core.py
- amico/info.py
- amico/models.py
- amico/preproc.py
- amico/util.py
- requirements.txt
- setup.py
This PR adds an attribute to the model base class that controls progress bars in the subclasses.
> Add ability to hide progress bars

- .cirrus.yml
- .github/workflows/build_wheels.yml
- .github/workflows/compile_openblas_linux.yml
- .github/workflows/compile_openblas_macos_x86_64.yml
- .github/workflows/macos_arm64_wheels.yml
Set up GitHub Actions and Cirrus CI to build platform wheels:
| Windows | MacOS | Linux |
|:-:|:-:|:-:|
| x86, x86_64 | x86_64, arm64 | x86_64, arm64 |
> ci: set up GH Actions and Cirrus CI
